<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../helpers.php';
redirect_if_not_logged_in();
ensure_maorin_workspace_tables($pdo);

function ws_configs(): array {
  return [
    'projects'=>['title'=>'Projects','table'=>'mb_projects','view'=>'view_projects','manage'=>'manage_projects','search'=>['project_code','name','client_name','location','status'],'fields'=>['project_code'=>'Code','name'=>'Project Name','client_name'=>'Client','location'=>'Location','project_type'=>'Type','status'=>'Status','progress_percent'=>'Progress %','estimated_cost'=>'Estimated Cost','actual_cost'=>'Actual Cost','contract_amount'=>'Contract Amount','notes'=>'Notes'],'money'=>['estimated_cost','actual_cost','contract_amount'],'required'=>['name']],
    'estimates'=>['title'=>'Estimates','table'=>'mb_estimates','view'=>'view_estimates','manage'=>'manage_estimates','search'=>['estimate_no','title','client_name','status'],'fields'=>['estimate_no'=>'Estimate No.','title'=>'Title','client_name'=>'Client','status'=>'Status','labor_cost'=>'Labor','material_cost'=>'Materials','equipment_cost'=>'Equipment','overhead_cost'=>'Overhead','markup_percent'=>'Markup %','tax_percent'=>'Tax %','notes'=>'Notes'],'money'=>['labor_cost','material_cost','equipment_cost','overhead_cost'],'required'=>['title']],
    'proposals'=>['title'=>'Proposals','table'=>'mb_proposals','view'=>'view_proposals','manage'=>'manage_proposals','search'=>['proposal_no','title','client_name','status'],'fields'=>['proposal_no'=>'Proposal No.','title'=>'Title','client_name'=>'Client','status'=>'Status','amount'=>'Amount','valid_until'=>'Valid Until','scope'=>'Scope','terms'=>'Terms'],'money'=>['amount'],'required'=>['title']],
    'plans'=>['title'=>'Plans','table'=>'mb_plan_files','view'=>'view_plans','manage'=>'manage_plans','search'=>['title','plan_type','revision','status'],'fields'=>['title'=>'Title','plan_type'=>'Plan Type','revision'=>'Revision','status'=>'Status','file_path'=>'File Path','notes'=>'Notes'],'money'=>[],'required'=>['title']],
    'expenses'=>['title'=>'Expenses','table'=>'mb_expenses','view'=>'view_finance','manage'=>'manage_expenses','search'=>['category','vendor','description','reference_no','status'],'fields'=>['expense_date'=>'Date','category'=>'Category','vendor'=>'Vendor','description'=>'Description','amount'=>'Amount','tax_amount'=>'Tax','reference_no'=>'Reference','status'=>'Status'],'money'=>['amount','tax_amount'],'required'=>['expense_date']],
    'invoices'=>['title'=>'Invoices','table'=>'mb_invoices','view'=>'view_finance','manage'=>'manage_invoices','search'=>['invoice_no','client_name','status','notes'],'fields'=>['invoice_no'=>'Invoice No.','client_name'=>'Client','issue_date'=>'Issue Date','due_date'=>'Due Date','amount'=>'Amount','paid_amount'=>'Paid','status'=>'Status','notes'=>'Notes'],'money'=>['amount','paid_amount'],'required'=>['issue_date']],
    'employees'=>['title'=>'Employees','table'=>'mb_employees','view'=>'view_hr','manage'=>'manage_employees','search'=>['employee_code','full_name','job_title','department','status'],'fields'=>['employee_code'=>'Code','full_name'=>'Full Name','employee_type'=>'Type','job_title'=>'Job Title','department'=>'Department','phone'=>'Phone','email'=>'Email','daily_rate'=>'Daily Rate','status'=>'Status','notes'=>'Notes'],'money'=>['daily_rate'],'required'=>['full_name']],
    'attendance'=>['title'=>'Attendance','table'=>'mb_attendance','view'=>'view_hr','manage'=>'manage_attendance','search'=>['status','notes'],'fields'=>['employee_id'=>'Employee ID','attendance_date'=>'Date','time_in'=>'Time In','time_out'=>'Time Out','status'=>'Status','notes'=>'Notes'],'money'=>[],'required'=>['employee_id','attendance_date']],
    'inventory'=>['title'=>'Inventory','table'=>'mb_inventory_items','view'=>'view_inventory','manage'=>'manage_inventory','search'=>['sku','item_name','category','location','status'],'fields'=>['sku'=>'SKU','item_name'=>'Item Name','category'=>'Category','unit'=>'Unit','quantity'=>'Qty','min_quantity'=>'Min Qty','unit_cost'=>'Unit Cost','location'=>'Location','status'=>'Status','notes'=>'Notes'],'money'=>['unit_cost'],'required'=>['item_name']],
    'documents'=>['title'=>'Documents','table'=>'mb_documents','view'=>'view_documents','manage'=>'manage_documents','search'=>['title','category','status','file_path','notes'],'fields'=>['title'=>'Title','category'=>'Category','status'=>'Status','file_path'=>'File Path','expiry_date'=>'Expiry Date','notes'=>'Notes'],'money'=>[],'required'=>['title']],
  ];
}
function h($v){return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');}
function module_config($m){$c=ws_configs(); if(!isset($c[$m])){http_response_code(404); exit('Unknown module.');} return $c[$m];}
function totals(PDO $pdo): array { return [
  'projects'=>(int)$pdo->query("SELECT COUNT(*) FROM mb_projects")->fetchColumn(),
  'contract'=>(float)$pdo->query("SELECT COALESCE(SUM(contract_amount),0) FROM mb_projects")->fetchColumn(),
  'expenses'=>(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM mb_expenses")->fetchColumn(),
  'inventory'=>(float)$pdo->query("SELECT COALESCE(SUM(quantity*unit_cost),0) FROM mb_inventory_items")->fetchColumn(),
  'employees'=>(int)$pdo->query("SELECT COUNT(*) FROM mb_employees WHERE status='active'")->fetchColumn(),
  'docs'=>(int)$pdo->query("SELECT COUNT(*) FROM mb_documents")->fetchColumn(),
];}
function render_overview(PDO $pdo): void { mb_require_any_permission($pdo,['view_projects','view_finance','view_hr','view_inventory','view_documents','view_reports']); $t=totals($pdo); ?>
<div class="row g-3 mb-3">
  <div class="col-md-4"><div class="workspace-stat"><div class="text-muted small">Projects</div><div class="fs-3 fw-bold"><?= $t['projects'] ?></div></div></div>
  <div class="col-md-4"><div class="workspace-stat"><div class="text-muted small">Contract Amount</div><div class="fs-3 fw-bold">₱<?= mb_money($t['contract']) ?></div></div></div>
  <div class="col-md-4"><div class="workspace-stat"><div class="text-muted small">Expenses</div><div class="fs-3 fw-bold">₱<?= mb_money($t['expenses']) ?></div></div></div>
  <div class="col-md-4"><div class="workspace-stat"><div class="text-muted small">Inventory Value</div><div class="fs-3 fw-bold">₱<?= mb_money($t['inventory']) ?></div></div></div>
  <div class="col-md-4"><div class="workspace-stat"><div class="text-muted small">Active Employees</div><div class="fs-3 fw-bold"><?= $t['employees'] ?></div></div></div>
  <div class="col-md-4"><div class="workspace-stat"><div class="text-muted small">Documents</div><div class="fs-3 fw-bold"><?= $t['docs'] ?></div></div></div>
</div>
<div class="alert alert-info mb-0">Use the Workspace dropdown in the main navigation or the tabs above. This screen stays in one page and loads modules without leaving the current website layout.</div>
<?php }
function render_reports(PDO $pdo): void { mb_require_any_permission($pdo,['view_reports']); $t=totals($pdo); ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-0">Reports Summary</h5><div class="text-muted small">Live totals from workspace records.</div></div></div>
<div class="table-responsive"><table class="table table-sm align-middle"><tbody>
<tr><th>Total Projects</th><td><?= $t['projects'] ?></td></tr><tr><th>Total Contract Amount</th><td>₱<?= mb_money($t['contract']) ?></td></tr><tr><th>Total Expenses</th><td>₱<?= mb_money($t['expenses']) ?></td></tr><tr><th>Estimated Gross Balance</th><td>₱<?= mb_money($t['contract']-$t['expenses']) ?></td></tr><tr><th>Inventory Value</th><td>₱<?= mb_money($t['inventory']) ?></td></tr><tr><th>Active Employees</th><td><?= $t['employees'] ?></td></tr></tbody></table></div>
<?php }
function render_module(PDO $pdo,string $m,string $q=''): void { $cfg=module_config($m); require_permission($pdo,$cfg['view']); $can=current_user_can($pdo,$cfg['manage']); $where=''; $params=[]; if($q!==''){ $likes=[]; foreach($cfg['search'] as $col){$likes[]="$col LIKE ?"; $params[]='%'.$q.'%';} $where='WHERE '.implode(' OR ',$likes);} $st=$pdo->prepare("SELECT * FROM {$cfg['table']} $where ORDER BY id DESC LIMIT 300"); $st->execute($params); $rows=$st->fetchAll(PDO::FETCH_ASSOC); $fields=$cfg['fields']; ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h5 class="mb-0"><?= h($cfg['title']) ?></h5><div class="text-muted small"><?= count($rows) ?> visible records</div></div><?php if($can): ?><button class="btn btn-primary btn-sm" data-workspace-open="wsModal">New <?= h(rtrim($cfg['title'],'s')) ?></button><?php endif; ?></div>
<div class="table-responsive workspace-table-wrap"><table class="table table-hover align-middle workspace-table"><thead><tr><?php $shown=array_slice(array_keys($fields),0,6); foreach($shown as $f): ?><th><?= h($fields[$f]) ?></th><?php endforeach; ?><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><?php foreach($shown as $f): ?><td><?= in_array($f,$cfg['money'],true)?'₱'.mb_money($r[$f]??0):h($r[$f]??'') ?></td><?php endforeach; ?><td class="text-end"><?php if($can): ?><button class="btn btn-sm btn-outline-danger" data-confirm-action="Delete this record?" data-id="<?= (int)$r['id'] ?>">Delete</button><?php endif; ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="<?= count($shown)+1 ?>" class="text-center text-muted py-4">No records found.</td></tr><?php endif; ?></tbody></table></div>
<?php if($can): ?><div class="modal fade" id="wsModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form class="modal-content" data-spa-form><input type="hidden" name="module" value="<?= h($m) ?>"><input type="hidden" name="action" value="save"><div class="modal-header"><h5 class="modal-title">New <?= h(rtrim($cfg['title'],'s')) ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><?php foreach($fields as $name=>$label): $isText=in_array($name,['notes','description','scope','terms'],true); $type=(str_contains($name,'date')||$name==='valid_until'||$name==='expiry_date')?'date':((str_contains($name,'time_'))?'time':(in_array($name,$cfg['money'],true)||str_contains($name,'percent')||str_contains($name,'quantity')||$name==='employee_id'?'number':'text')); ?><div class="col-md-6 <?= $isText?'col-12':'' ?>"><label class="form-label small fw-semibold"><?= h($label) ?></label><?php if($isText): ?><textarea class="form-control" name="<?= h($name) ?>" rows="3"></textarea><?php else: ?><input class="form-control" name="<?= h($name) ?>" type="<?= $type ?>" <?= $type==='number'?'step="0.01"':'' ?> <?= in_array($name,$cfg['required'],true)?'required':'' ?>></input><?php endif; ?></div><?php endforeach; ?></div></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div><?php endif; ?>
<?php }
if($_SERVER['REQUEST_METHOD']==='POST'){
  header('Content-Type: application/json');
  try{ csrf_verify(); $m=$_POST['module']??''; $cfg=module_config($m); require_permission($pdo,$cfg['manage']); $action=$_POST['action']??''; if($action==='delete'){ $id=(int)($_POST['id']??0); $pdo->prepare("DELETE FROM {$cfg['table']} WHERE id=?")->execute([$id]); echo json_encode(['ok'=>true,'message'=>'Record deleted.']); exit; }
    if($action==='save'){ foreach($cfg['required'] as $req){ if(trim((string)($_POST[$req]??''))==='') throw new RuntimeException($cfg['fields'][$req].' is required.'); } $cols=array_keys($cfg['fields']); $vals=[]; foreach($cols as $col){$v=$_POST[$col]??null; $vals[]=$v===''?null:$v;} if(isset($cfg['fields']['created_by'])){} $sql="INSERT INTO {$cfg['table']} (".implode(',',$cols).") VALUES (".implode(',',array_fill(0,count($cols),'?')).")"; if($m==='estimates'){ $subtotal=(float)($_POST['labor_cost']??0)+(float)($_POST['material_cost']??0)+(float)($_POST['equipment_cost']??0)+(float)($_POST['overhead_cost']??0); $markup=$subtotal*((float)($_POST['markup_percent']??0)/100); $tax=($subtotal+$markup)*((float)($_POST['tax_percent']??0)/100); $cols=array_merge($cols,['subtotal','markup_amount','tax_amount','grand_total','created_by']); $vals=array_merge($vals,[$subtotal,$markup,$tax,$subtotal+$markup+$tax,(int)$_SESSION['user_id']]); $sql="INSERT INTO {$cfg['table']} (".implode(',',$cols).") VALUES (".implode(',',array_fill(0,count($cols),'?')).")"; } elseif(in_array($m,['projects','proposals','expenses','invoices','documents','plans'],true)){ $cols[]='created_by'; $vals[]=(int)$_SESSION['user_id']; $sql="INSERT INTO {$cfg['table']} (".implode(',',$cols).") VALUES (".implode(',',array_fill(0,count($cols),'?')).")"; } $pdo->prepare($sql)->execute($vals); echo json_encode(['ok'=>true,'message'=>'Record saved.']); exit; }
    throw new RuntimeException('Unknown action.');
  }catch(Throwable $e){ http_response_code(400); echo json_encode(['ok'=>false,'message'=>$e->getMessage()]); exit; }
}
$module=$_GET['module']??'overview'; $q=trim((string)($_GET['q']??''));
if($module==='overview') render_overview($pdo); elseif($module==='reports') render_reports($pdo); else render_module($pdo,$module,$q);
