<?php
require_once __DIR__ . '/../../config.php';
redirect_if_not_logged_in();
mb_require_any_permission($pdo, ['view_projects','manage_projects']);
require_once __DIR__ . '/../_shared/workspace.php';
ensure_maorin_workspace_tables($pdo);
$canManage = current_user_can($pdo, 'manage_projects');
$edit = null;
if ($_SERVER['REQUEST_METHOD']==='POST' && $canManage) {
  try { csrf_verify(); $action=$_POST['action'] ?? '';
    if ($action==='save') {
      $id=(int)($_POST['id'] ?? 0);
      $data=[trim($_POST['project_code'] ?? '') ?: null, trim($_POST['name'] ?? ''), trim($_POST['client_name'] ?? ''), trim($_POST['client_email'] ?? ''), trim($_POST['client_phone'] ?? ''), trim($_POST['location'] ?? ''), trim($_POST['project_type'] ?? ''), trim($_POST['status'] ?? 'proposed'), max(0,min(100,(int)($_POST['progress_percent'] ?? 0))), $_POST['start_date'] ?: null, $_POST['target_end_date'] ?: null, (float)($_POST['estimated_cost'] ?? 0), (float)($_POST['actual_cost'] ?? 0), (float)($_POST['contract_amount'] ?? 0), trim($_POST['notes'] ?? '')];
      if ($data[1]==='') throw new RuntimeException('Project name is required.');
      if ($id>0) { $st=$pdo->prepare("UPDATE mb_projects SET project_code=?, name=?, client_name=?, client_email=?, client_phone=?, location=?, project_type=?, status=?, progress_percent=?, start_date=?, target_end_date=?, estimated_cost=?, actual_cost=?, contract_amount=?, notes=? WHERE id=?"); $st->execute([...$data,$id]); mb_set_success('Project updated.'); }
      else { $st=$pdo->prepare("INSERT INTO mb_projects (project_code,name,client_name,client_email,client_phone,location,project_type,status,progress_percent,start_date,target_end_date,estimated_cost,actual_cost,contract_amount,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); $st->execute([...$data,(int)$_SESSION['user_id']]); mb_set_success('Project created.'); }
    } elseif ($action==='delete') { $id=(int)($_POST['id'] ?? 0); $pdo->prepare("DELETE FROM mb_projects WHERE id=?")->execute([$id]); mb_set_success('Project deleted.'); }
    elseif ($action==='progress') { $id=(int)($_POST['project_id'] ?? 0); $pct=max(0,min(100,(int)($_POST['progress_percent'] ?? 0))); $cost=(float)($_POST['cost_added'] ?? 0); $pdo->prepare("INSERT INTO mb_project_updates (project_id,update_date,title,progress_percent,cost_added,details,created_by) VALUES (?,?,?,?,?,?,?)")->execute([$id,$_POST['update_date'] ?: date('Y-m-d'),trim($_POST['title'] ?? 'Progress update'),$pct,$cost,trim($_POST['details'] ?? ''),(int)$_SESSION['user_id']]); $pdo->prepare("UPDATE mb_projects SET progress_percent=?, actual_cost=actual_cost+? WHERE id=?")->execute([$pct,$cost,$id]); mb_set_success('Progress update saved.'); }
  } catch(Throwable $e){ mb_set_error($e->getMessage()); }
  mb_redirect('index.php');
}
if (isset($_GET['edit'])) { $st=$pdo->prepare("SELECT * FROM mb_projects WHERE id=?"); $st->execute([(int)$_GET['edit']]); $edit=$st->fetch(PDO::FETCH_ASSOC); }
$q=trim($_GET['q'] ?? ''); $where=''; $params=[]; if($q!==''){ $where="WHERE name LIKE ? OR client_name LIKE ? OR project_code LIKE ? OR status LIKE ?"; $like="%$q%"; $params=[$like,$like,$like,$like]; }
$st=$pdo->prepare("SELECT *, (contract_amount-actual_cost) AS profit FROM mb_projects $where ORDER BY updated_at DESC, id DESC"); $st->execute($params); $rows=$st->fetchAll(PDO::FETCH_ASSOC);
$tot=$pdo->query("SELECT COUNT(*) c, COALESCE(SUM(contract_amount),0) contract, COALESCE(SUM(actual_cost),0) cost FROM mb_projects")->fetch(PDO::FETCH_ASSOC);
[$ok,$err]=mb_flash(); mb_workspace_header($pdo,'Projects','Projects'); ?>
<?php if($ok): ?><div class="alert alert-success"><?= htmlspecialchars($ok) ?></div><?php endif; ?><?php if($err): ?><div class="alert alert-danger"><?= htmlspecialchars($err) ?></div><?php endif; ?>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="mb-stat"><div class="mb-stat-label">Projects</div><div class="mb-stat-value"><?= (int)$tot['c'] ?></div></div></div><div class="col-md-4"><div class="mb-stat"><div class="mb-stat-label">Contract Amount</div><div class="mb-stat-value">₱<?= mb_money($tot['contract']) ?></div></div></div><div class="col-md-4"><div class="mb-stat"><div class="mb-stat-label">Cost / Profit</div><div class="mb-stat-value">₱<?= mb_money($tot['cost']) ?> / ₱<?= mb_money(((float)$tot['contract'])-((float)$tot['cost'])) ?></div></div></div></div>
<div class="mb-card mb-3"><div class="mb-card-header"><form class="mb-toolbar" method="get"><input class="form-control mb-search" name="q" value="<?= htmlspecialchars($q) ?>" placeholder="Search projects, clients, status"><button class="btn btn-outline-secondary">Search</button></form><?php if($canManage): ?><button class="btn btn-primary" data-mb-open-modal="projectModal">New Project</button><?php endif; ?></div><div class="table-responsive"><table class="table mb-table"><thead><tr><th>Code</th><th>Project</th><th>Client</th><th>Status</th><th>Progress</th><th>Contract</th><th>Actual Cost</th><th>Profit</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= htmlspecialchars($r['project_code'] ?: '-') ?></td><td><strong><?= htmlspecialchars($r['name']) ?></strong><div class="text-muted small"><?= htmlspecialchars($r['location'] ?: '') ?></div></td><td><?= htmlspecialchars($r['client_name'] ?: '-') ?></td><td><span class="mb-badge <?= in_array($r['status'],['completed','approved'])?'success':(in_array($r['status'],['paused','cancelled'])?'danger':'warn') ?>"><?= htmlspecialchars($r['status']) ?></span></td><td><div class="progress" style="height:8px"><div class="progress-bar" style="width:<?= (int)$r['progress_percent'] ?>%"></div></div><div class="small text-muted"><?= (int)$r['progress_percent'] ?>%</div></td><td>₱<?= mb_money($r['contract_amount']) ?></td><td>₱<?= mb_money($r['actual_cost']) ?></td><td>₱<?= mb_money($r['profit']) ?></td><td class="mb-actions"><?php if($canManage): ?><a class="btn btn-sm btn-outline-primary" href="?edit=<?= (int)$r['id'] ?>">Edit</a><button class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#progressModal" data-project-id="<?= (int)$r['id'] ?>">Update</button><form method="post" class="d-inline"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger" data-confirm="Delete this project?">Delete</button></form><?php endif; ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="9" class="text-center text-muted py-4">No projects found.</td></tr><?php endif; ?></tbody></table></div></div>
<div class="modal fade" id="projectModal"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form method="post" class="modal-content mb-modal-panel"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id'] ?? 0) ?>"><div class="modal-header"><h5 class="modal-title"><?= $edit?'Edit':'New' ?> Project</h5><button class="btn-close" data-bs-dismiss="modal" type="button"></button></div><div class="modal-body"><div class="mb-form-grid"><label>Code<input class="form-control" name="project_code" value="<?= htmlspecialchars($edit['project_code'] ?? '') ?>"></label><label>Project Name<input required class="form-control" name="name" value="<?= htmlspecialchars($edit['name'] ?? '') ?>"></label><label>Client Name<input class="form-control" name="client_name" value="<?= htmlspecialchars($edit['client_name'] ?? '') ?>"></label><label>Client Email<input class="form-control" name="client_email" value="<?= htmlspecialchars($edit['client_email'] ?? '') ?>"></label><label>Client Phone<input class="form-control" name="client_phone" value="<?= htmlspecialchars($edit['client_phone'] ?? '') ?>"></label><label>Location<input class="form-control" name="location" value="<?= htmlspecialchars($edit['location'] ?? '') ?>"></label><label>Type<input class="form-control" name="project_type" value="<?= htmlspecialchars($edit['project_type'] ?? '') ?>"></label><label>Status<select class="form-select" name="status"><?php foreach(['proposed','approved','ongoing','paused','completed','cancelled'] as $v): ?><option <?= (($edit['status'] ?? '')===$v?'selected':'') ?>><?= $v ?></option><?php endforeach; ?></select></label><label>Progress %<input class="form-control" type="number" min="0" max="100" name="progress_percent" value="<?= htmlspecialchars($edit['progress_percent'] ?? '0') ?>"></label><label>Start Date<input class="form-control" type="date" name="start_date" value="<?= htmlspecialchars($edit['start_date'] ?? '') ?>"></label><label>Target End<input class="form-control" type="date" name="target_end_date" value="<?= htmlspecialchars($edit['target_end_date'] ?? '') ?>"></label><label>Estimated Cost<input class="form-control" type="number" step="0.01" name="estimated_cost" value="<?= htmlspecialchars($edit['estimated_cost'] ?? '0') ?>"></label><label>Actual Cost<input class="form-control" type="number" step="0.01" name="actual_cost" value="<?= htmlspecialchars($edit['actual_cost'] ?? '0') ?>"></label><label>Contract Amount<input class="form-control" type="number" step="0.01" name="contract_amount" value="<?= htmlspecialchars($edit['contract_amount'] ?? '0') ?>"></label><label class="full">Notes<textarea class="form-control" name="notes" rows="4"><?= htmlspecialchars($edit['notes'] ?? '') ?></textarea></label></div></div><div class="modal-footer"><button class="btn btn-primary">Save Project</button></div></form></div></div>
<div class="modal fade" id="progressModal"><div class="modal-dialog"><form method="post" class="modal-content mb-modal-panel"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="action" value="progress"><input type="hidden" name="project_id" id="progressProjectId"><div class="modal-header"><h5 class="modal-title">Project Progress Update</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Date<input class="form-control" type="date" name="update_date" value="<?= date('Y-m-d') ?>"></label><label class="form-label w-100">Title<input class="form-control" name="title" required></label><label class="form-label w-100">Progress %<input class="form-control" type="number" min="0" max="100" name="progress_percent" required></label><label class="form-label w-100">Cost Added<input class="form-control" type="number" step="0.01" name="cost_added" value="0"></label><label class="form-label w-100">Details<textarea class="form-control" name="details"></textarea></label></div><div class="modal-footer"><button class="btn btn-primary">Save Update</button></div></form></div></div>
<script>document.getElementById('progressModal')?.addEventListener('show.bs.modal',e=>{document.getElementById('progressProjectId').value=e.relatedTarget?.dataset.projectId||''});<?php if($edit): ?>new bootstrap.Modal(document.getElementById('projectModal')).show();<?php endif; ?></script>
<?php mb_workspace_footer(); ?>