CREATE TABLE IF NOT EXISTS accounting_journal_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  journal_type VARCHAR(40) NOT NULL,
  user_id INT NULL,
  entry_date DATE NOT NULL,
  journal_no VARCHAR(60) NULL,
  particulars TEXT NULL,
  ref_page VARCHAR(80) NULL,
  jv_no VARCHAR(120) NULL,
  client_name VARCHAR(180) NULL,
  supplier VARCHAR(180) NULL,
  party_name VARCHAR(180) NULL,
  invoice_no VARCHAR(120) NULL,
  sales_invoice_no VARCHAR(120) NULL,
  voucher_no VARCHAR(120) NULL,
  reference_no VARCHAR(120) NULL,
  tin VARCHAR(80) NULL,
  vat_nvat VARCHAR(40) NULL,
  goods_service VARCHAR(80) NULL,
  address VARCHAR(255) NULL,
  project_id VARCHAR(120) NULL,
  entry_type VARCHAR(120) NULL,
  account_title VARCHAR(180) NOT NULL,
  description TEXT NULL,
  project_name VARCHAR(180) NULL,
  payment_method VARCHAR(80) NULL,
  debit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  credit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  cash_in DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  cash_out DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  sundry_account_title VARCHAR(180) NULL,
  sundry_debit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  sundry_credit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  remarks TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_accounting_journal_type_date (journal_type, entry_date),
  INDEX idx_accounting_journal_user (user_id),
  INDEX idx_accounting_journal_no (journal_no)
);
