ALTER TABLE `website_projects`
  ADD COLUMN IF NOT EXISTS `description` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `is_published` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `display_order` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `seo_title` VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS `seo_description` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT NULL,
  ADD COLUMN IF NOT EXISTS `updated_by` INT NULL,
  ADD COLUMN IF NOT EXISTS `internal_project_id` INT NULL;

ALTER TABLE `website_project_media`
  ADD COLUMN IF NOT EXISTS `caption` VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS `alt_text` VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS `sort_order` INT NOT NULL DEFAULT 0;
